export const departments = ['Engineering', 'Design', 'Delivery', 'QA', 'Marketing', 'HR', 'Leadership']

export const employees = [
  {
    id: 'emp-1',
    name: 'Jidnyasa Girase',
    email: 'jidnyasa.girase@technova.in',
    phone: '+91 98765 43210',
    department: 'Leadership',
    designation: 'Founder & CEO',
    status: 'active',
    joiningDate: '2021-04-01',
    skills: ['Strategy', 'Sales', 'Product'],
    projects: 4,
    employeeCode: 'TN-0001',
    dob: '1985-03-14',
    gender: 'Male',
    address: 'Baner, Pune, Maharashtra 411045',
    emergencyContact: { name: 'Mahesh Girase', phone: '+91 98765 43211', relation: 'Spouse' },
    manager: 'Board',
    employmentType: 'Full-time',
    location: 'Pune HQ',
    avatar: null,
  },
  {
    id: 'emp-2',
    name: 'Jay Girase',
    email: 'jay.girase@technova.in',
    phone: '+91 98220 11223',
    department: 'Delivery',
    designation: 'Project Manager',
    status: 'active',
    joiningDate: '2021-09-14',
    skills: ['Scrum', 'Client Management', 'JIRA'],
    projects: 5,
    employeeCode: 'TN-0007',
    dob: '1990-07-22',
    gender: 'Female',
    address: 'Kothrud, Pune, Maharashtra 411038',
    emergencyContact: { name: 'Rajesh Girase', phone: '+91 98220 11224', relation: 'Father' },
    manager: 'Jidnyasa Girase',
    employmentType: 'Full-time',
    location: 'Pune HQ',
    avatar: null,
  },
  {
    id: 'emp-3',
    name: 'Rohit Girase',
    email: 'rohit.girase@technova.in',
    phone: '+91 90210 55678',
    department: 'Engineering',
    designation: 'Senior Frontend Developer',
    status: 'active',
    joiningDate: '2022-01-10',
    skills: ['React', 'JavaScript', 'Tailwind CSS'],
    projects: 3,
    employeeCode: 'TN-0012',
    dob: '1994-11-05',
    gender: 'Male',
    address: 'Viman Nagar, Pune, Maharashtra 411014',
    emergencyContact: { name: 'Anita Girase', phone: '+91 90210 55679', relation: 'Mother' },
    manager: 'Jay Girase',
    employmentType: 'Full-time',
    location: 'Hybrid',
    avatar: null,
  },
  {
    id: 'emp-4',
    name: 'Sneha Joshi',
    email: 'sneha.joshi@technova.in',
    phone: '+91 90210 99887',
    department: 'Design',
    designation: 'UI/UX Designer',
    status: 'active',
    joiningDate: '2022-03-21',
    skills: ['Figma', 'Design Systems', 'Prototyping'],
    projects: 4,
    employeeCode: 'TN-0015',
    dob: '1996-02-18',
    gender: 'Female',
    address: 'Aundh, Pune, Maharashtra 411007',
    emergencyContact: { name: 'Mahesh Joshi', phone: '+91 90210 99880', relation: 'Father' },
    manager: 'Jay Girase',
    employmentType: 'Full-time',
    location: 'Remote',
    avatar: null,
  },
  {
    id: 'emp-5',
    name: 'Amit Kulkarni',
    email: 'amit.kulkarni@technova.in',
    phone: '+91 91234 22110',
    department: 'Engineering',
    designation: 'Backend Developer',
    status: 'active',
    joiningDate: '2022-07-04',
    skills: ['Python', 'FastAPI', 'MySQL'],
    projects: 3,
    employeeCode: 'TN-0019',
    dob: '1993-09-09',
    gender: 'Male',
    address: 'Hinjewadi, Pune, Maharashtra 411057',
    emergencyContact: { name: 'Snehal Kulkarni', phone: '+91 91234 22111', relation: 'Spouse' },
    manager: 'Jay Girase',
    employmentType: 'Full-time',
    location: 'Pune HQ',
    avatar: null,
  },
  {
    id: 'emp-6',
    name: 'Tanvi Deshpande',
    email: 'tanvi.deshpande@technova.in',
    phone: '+91 89998 12345',
    department: 'QA',
    designation: 'QA Engineer',
    status: 'active',
    joiningDate: '2023-02-13',
    skills: ['Manual Testing', 'Automation', 'Cypress'],
    projects: 4,
    employeeCode: 'TN-0024',
    dob: '1997-05-30',
    gender: 'Female',
    address: 'Wakad, Pune, Maharashtra 411057',
    emergencyContact: { name: 'Prakash Deshpande', phone: '+91 89998 12346', relation: 'Father' },
    manager: 'Jay Girase',
    employmentType: 'Full-time',
    location: 'Pune HQ',
    avatar: null,
  },
  {
    id: 'emp-7',
    name: 'Karthik Reddy',
    email: 'karthik.reddy@technova.in',
    phone: '+91 91567 87654',
    department: 'Engineering',
    designation: 'DevOps Engineer',
    status: 'on_leave',
    joiningDate: '2022-11-02',
    skills: ['CI/CD', 'Linux', 'Nginx'],
    projects: 2,
    employeeCode: 'TN-0021',
    dob: '1992-12-01',
    gender: 'Male',
    address: 'Madhapur, Hyderabad, Telangana 500081',
    emergencyContact: { name: 'Lakshmi Reddy', phone: '+91 91567 87655', relation: 'Mother' },
    manager: 'Amit Kulkarni',
    employmentType: 'Full-time',
    location: 'Remote',
    avatar: null,
  },
  {
    id: 'emp-8',
    name: 'Pooja Nair',
    email: 'pooja.nair@technova.in',
    phone: '+91 90333 44556',
    department: 'Marketing',
    designation: 'Marketing Executive',
    status: 'active',
    joiningDate: '2023-06-19',
    skills: ['SEO', 'Content', 'Campaigns'],
    projects: 1,
    employeeCode: 'TN-0028',
    dob: '1998-08-12',
    gender: 'Female',
    address: 'Koregaon Park, Pune, Maharashtra 411001',
    emergencyContact: { name: 'Suresh Nair', phone: '+91 90333 44557', relation: 'Father' },
    manager: 'Jidnyasa Girase',
    employmentType: 'Full-time',
    location: 'Pune HQ',
    avatar: null,
  },
  {
    id: 'emp-9',
    name: 'Ishaan Verma',
    email: 'ishaan.verma@technova.in',
    phone: '+91 98230 66778',
    department: 'Engineering',
    designation: 'Full Stack Developer',
    status: 'active',
    joiningDate: '2026-07-01',
    skills: ['Node.js', 'React', 'PostgreSQL'],
    projects: 0,
    employeeCode: 'TN-0041',
    dob: '1999-04-25',
    gender: 'Male',
    address: 'Pimple Saudagar, Pune, Maharashtra 411027',
    emergencyContact: { name: 'Neeta Verma', phone: '+91 98230 66779', relation: 'Mother' },
    manager: 'Amit Kulkarni',
    employmentType: 'Probation',
    location: 'Pune HQ',
    avatar: null,
  },
  {
    id: 'emp-10',
    name: 'Meera Iyer',
    email: 'meera.iyer@technova.in',
    phone: '+91 97654 32109',
    department: 'HR',
    designation: 'HR Manager',
    status: 'active',
    joiningDate: '2022-05-16',
    skills: ['Recruitment', 'Payroll', 'Employee Engagement'],
    projects: 0,
    employeeCode: 'TN-0016',
    dob: '1991-01-19',
    gender: 'Female',
    address: 'Balewadi, Pune, Maharashtra 411045',
    emergencyContact: { name: 'Venkat Iyer', phone: '+91 97654 32100', relation: 'Spouse' },
    manager: 'Jidnyasa Girase',
    employmentType: 'Full-time',
    location: 'Pune HQ',
    avatar: null,
  },
  {
    id: 'emp-11',
    name: 'Rohan Gupta',
    email: 'rohan.gupta@technova.in',
    phone: '+91 99887 76655',
    department: 'Design',
    designation: 'Graphic Designer',
    status: 'active',
    joiningDate: '2026-08-10',
    skills: ['Illustrator', 'Branding', 'Motion Design'],
    projects: 1,
    employeeCode: 'TN-0044',
    dob: '2000-10-03',
    gender: 'Male',
    address: 'Karve Nagar, Pune, Maharashtra 411052',
    emergencyContact: { name: 'Rekha Gupta', phone: '+91 99887 76600', relation: 'Mother' },
    manager: 'Sneha Joshi',
    employmentType: 'Probation',
    location: 'Hybrid',
    avatar: null,
  },
  {
    id: 'emp-12',
    name: 'Ananya Bhat',
    email: 'ananya.bhat@technova.in',
    phone: '+91 96543 21098',
    department: 'Delivery',
    designation: 'Business Analyst',
    status: 'inactive',
    joiningDate: '2023-03-06',
    skills: ['Requirement Analysis', 'SQL', 'Process Mapping'],
    projects: 0,
    employeeCode: 'TN-0027',
    dob: '1995-06-28',
    gender: 'Female',
    address: 'Sadashiv Peth, Pune, Maharashtra 411030',
    emergencyContact: { name: 'Ramesh Bhat', phone: '+91 96543 21000', relation: 'Father' },
    manager: 'Jay Girase',
    employmentType: 'Full-time',
    location: 'Pune HQ',
    avatar: null,
  },
]

export function getEmployeeById(id) {
  return employees.find((e) => e.id === id)
}
