export const LEAD_STATUSES = ['new', 'contacted', 'qualified', 'proposal', 'negotiation', 'won', 'lost']

export const leads = [
  {
    id: 'ld-1',
    name: 'Vikram Anand',
    company: 'Orbit Logistics',
    email: 'vikram.anand@orbitlogistics.in',
    phone: '+91 98450 12233',
    source: 'Website',
    status: 'new',
    value: 450000,
    owner: 'Jay Girase',
    lastContact: '2026-09-15',
    nextFollowUp: '2026-09-24',
    priority: 'high',
    notes: 'Interested in a custom logistics tracking dashboard.',
  },
  {
    id: 'ld-2',
    name: 'Ishaan Kapoor',
    company: 'Vertex Realty',
    email: 'ishaan@vertexrealty.com',
    phone: '+91 90123 88990',
    source: 'Referral',
    status: 'contacted',
    value: 620000,
    owner: 'Jay Girase',
    lastContact: '2026-09-17',
    nextFollowUp: '2026-09-23',
    priority: 'medium',
    notes: 'Wants a CRM + property listing portal.',
  },
  {
    id: 'ld-3',
    name: 'Meera Nair',
    company: 'GreenLeaf Organics',
    email: 'meera@greenleaforganics.in',
    phone: '+91 88990 12345',
    source: 'LinkedIn',
    status: 'qualified',
    value: 310000,
    owner: 'Jidnyasa Girase',
    lastContact: '2026-09-14',
    nextFollowUp: '2026-09-26',
    priority: 'medium',
    notes: 'E-commerce platform with subscription billing.',
  },
  {
    id: 'ld-4',
    name: 'Arjun Malhotra',
    company: 'Pinnacle Consulting',
    email: 'arjun@pinnacleconsulting.co.in',
    phone: '+91 99887 44556',
    source: 'Cold Outreach',
    status: 'proposal',
    value: 890000,
    owner: 'Jay Girase',
    lastContact: '2026-09-12',
    nextFollowUp: '2026-09-22',
    priority: 'high',
    notes: 'Proposal sent for internal workflow automation suite.',
  },
  {
    id: 'ld-5',
    name: 'Kavya Iyer',
    company: 'Solstice Wellness',
    email: 'kavya@solsticewellness.in',
    phone: '+91 97123 65478',
    source: 'Event',
    status: 'negotiation',
    value: 275000,
    owner: 'Jidnyasa Girase',
    lastContact: '2026-09-18',
    nextFollowUp: '2026-09-25',
    priority: 'medium',
    notes: 'Negotiating scope for booking + membership app.',
  },
  {
    id: 'ld-6',
    name: 'Devansh Gupta',
    company: 'Nimbus Freight',
    email: 'devansh@nimbusfreight.com',
    phone: '+91 96543 21098',
    source: 'Website',
    status: 'won',
    value: 540000,
    owner: 'Jay Girase',
    lastContact: '2026-09-05',
    nextFollowUp: null,
    priority: 'high',
    notes: 'Converted to client — kicking off discovery next week.',
  },
  {
    id: 'ld-7',
    name: 'Simran Kaur',
    company: 'Lumen Interiors',
    email: 'simran@luminteriors.in',
    phone: '+91 90876 54321',
    source: 'Referral',
    status: 'lost',
    value: 180000,
    owner: 'Jidnyasa Girase',
    lastContact: '2026-08-29',
    nextFollowUp: null,
    priority: 'low',
    notes: 'Went with an in-house team instead.',
  },
  {
    id: 'ld-8',
    name: 'Rohit Bansal',
    company: 'Quantify Analytics',
    email: 'rohit@quantifyanalytics.io',
    phone: '+91 89123 45670',
    source: 'LinkedIn',
    status: 'contacted',
    value: 720000,
    owner: 'Jay Girase',
    lastContact: '2026-09-19',
    nextFollowUp: '2026-09-27',
    priority: 'high',
    notes: 'Needs a data visualization dashboard for internal reporting.',
  },
]

export function getLeadById(id) {
  return leads.find((l) => l.id === id)
}
