export const payments = [
  { id: 'pay-1', number: 'PAY-1042', invoice: 'INV-2026-00118', client: 'BrightPixel Labs', amount: 250000, date: '2026-08-14', method: 'Bank Transfer', status: 'completed', reference: 'NEFT/HDFC/2608140457' },
  { id: 'pay-2', number: 'PAY-1051', invoice: 'INV-2026-00109', client: 'CloudMatrix Technologies', amount: 480000, date: '2026-07-24', method: 'UPI', status: 'completed', reference: 'UPI/420817263541' },
  { id: 'pay-3', number: 'PAY-1063', invoice: 'INV-2026-00136', client: 'Meridian Retail Pvt Ltd', amount: 78000, date: '2026-09-16', method: 'Credit Card', status: 'completed', reference: 'CC/AUTH/778120' },
  { id: 'pay-4', number: 'PAY-1070', invoice: 'INV-2026-00124', client: 'BrightPixel Labs', amount: 60000, date: '2026-09-19', method: 'Bank Transfer', status: 'pending', reference: 'IMPS/ICICI/2609190312' },
  { id: 'pay-5', number: 'PAY-1068', invoice: 'INV-2026-00131', client: 'InnoSoft Systems', amount: 120000, date: '2026-09-10', method: 'UPI', status: 'failed', reference: 'UPI/420898112204' },
]

export const expenses = [
  { id: 'exp-1', title: 'AWS hosting — September', category: 'Infrastructure', amount: 42500, date: '2026-09-05', employee: 'Amit Kulkarni', project: 'CRM Implementation', description: 'Monthly EC2, RDS and S3 charges for the CRM staging and production environments.', attachment: 'AWS_Invoice_Sep2026.pdf' },
  { id: 'exp-2', title: 'Figma team subscription', category: 'Software', amount: 18000, date: '2026-09-01', employee: 'Sneha Joshi', project: null, description: 'Annual renewal of 5 Figma professional seats for the design team.', attachment: 'Figma_Receipt.pdf' },
  { id: 'exp-3', title: 'Client dinner — BrightPixel', category: 'Client Entertainment', amount: 6800, date: '2026-09-12', employee: 'Jidnyasa Girase', project: 'Corporate Website Redesign', description: 'Dinner with the BrightPixel leadership team after the Milestone 2 demo.', attachment: null },
  { id: 'exp-4', title: 'Domain & SSL renewal', category: 'Infrastructure', amount: 9200, date: '2026-08-28', employee: 'Rohit Girase', project: 'Corporate Website Redesign', description: 'Renewal of the client domain and wildcard SSL certificate.', attachment: 'GoDaddy_Renewal.png' },
  { id: 'exp-5', title: 'Team offsite — Q3', category: 'Team Building', amount: 85000, date: '2026-09-08', employee: 'Jay Girase', project: null, description: 'Two-day offsite at Lonavala for the delivery and engineering teams.', attachment: 'Offsite_Bills.pdf' },
  { id: 'exp-6', title: 'Client visit — Bengaluru flights', category: 'Travel', amount: 23400, date: '2026-08-19', employee: 'Jay Girase', project: 'CRM Implementation', description: 'Return flights Pune to Bengaluru for the CloudMatrix requirements workshop.', attachment: 'IndiGo_Tickets.pdf' },
  { id: 'exp-7', title: 'Google Workspace — 15 seats', category: 'Software', amount: 21600, date: '2026-08-03', employee: 'Meera Iyer', project: null, description: 'Quarterly Google Workspace Business Standard subscription.', attachment: 'Workspace_Invoice.pdf' },
  { id: 'exp-8', title: 'LinkedIn & Google Ads campaign', category: 'Marketing', amount: 34500, date: '2026-07-22', employee: 'Pooja Nair', project: null, description: 'Lead generation campaign for the Q3 IT services push.', attachment: null },
  { id: 'exp-9', title: 'Device testing — Android handsets', category: 'Office Supplies', amount: 28900, date: '2026-07-14', employee: 'Tanvi Deshpande', project: 'Mobile Application — InnoSoft', description: 'Two mid-range Android handsets purchased for regression testing.', attachment: 'Croma_Invoice.pdf' },
  { id: 'exp-10', title: 'Sentry & Datadog monitoring', category: 'Software', amount: 15200, date: '2026-07-05', employee: 'Karthik Reddy', project: 'CRM Implementation', description: 'Error tracking and uptime monitoring for CRM staging.', attachment: null },
  { id: 'exp-11', title: 'Co-working day passes — Hinjewadi', category: 'Other', amount: 7200, date: '2026-06-18', employee: 'Ishaan Verma', project: 'E-commerce Platform', description: 'Day passes during the office power maintenance shutdown.', attachment: null },
  { id: 'exp-12', title: 'AWS hosting — June', category: 'Infrastructure', amount: 36800, date: '2026-06-05', employee: 'Amit Kulkarni', project: 'Corporate Website Redesign', description: 'Monthly cloud infrastructure charges.', attachment: 'AWS_Invoice_Jun2026.pdf' },
  { id: 'exp-13', title: 'Team lunch — sprint release', category: 'Team Building', amount: 11400, date: '2026-05-29', employee: 'Jay Girase', project: 'Corporate Website Redesign', description: 'Team lunch to celebrate the homepage go-live.', attachment: null },
  { id: 'exp-14', title: 'Conference tickets — React India', category: 'Travel', amount: 48000, date: '2026-05-10', employee: 'Rohit Girase', project: null, description: 'Tickets and stay for two engineers at React India, Goa.', attachment: 'Conference_Receipts.pdf' },
]

export const quotations = [
  {
    id: 'quo-1',
    number: 'QUO-2026-041',
    client: 'Orbit Logistics',
    clientId: null,
    amount: 450000,
    status: 'sent',
    issueDate: '2026-09-16',
    validUntil: '2026-10-01',
    taxPercent: 0,
    notes: 'Includes 3 months of post-launch support.',
    items: [
      { description: 'Fleet tracking dashboard — design & development', qty: 1, price: 380000 },
      { description: 'Driver mobile app (Android)', qty: 1, price: 70000 },
    ],
  },
  {
    id: 'quo-2',
    number: 'QUO-2026-039',
    client: 'Vertex Realty',
    clientId: null,
    amount: 620000,
    status: 'accepted',
    issueDate: '2026-09-08',
    validUntil: '2026-09-22',
    taxPercent: 0,
    notes: '50% advance payable on acceptance.',
    items: [
      { description: 'Property listing portal with admin panel', qty: 1, price: 520000 },
      { description: 'Lead capture & CRM integration', qty: 1, price: 100000 },
    ],
  },
  {
    id: 'quo-3',
    number: 'QUO-2026-036',
    client: 'Pinnacle Consulting',
    clientId: null,
    amount: 890000,
    status: 'expired',
    issueDate: '2026-09-01',
    validUntil: '2026-09-20',
    taxPercent: 0,
    notes: '',
    items: [
      { description: 'Consulting practice website & knowledge hub', qty: 1, price: 640000 },
      { description: 'Client portal with document sharing', qty: 1, price: 250000 },
    ],
  },
  {
    id: 'quo-4',
    number: 'QUO-2026-028',
    client: 'Lumen Interiors',
    clientId: null,
    amount: 180000,
    status: 'rejected',
    issueDate: '2026-08-14',
    validUntil: '2026-08-29',
    taxPercent: 0,
    notes: 'Client chose an in-house template solution.',
    items: [{ description: 'Portfolio website with 3D gallery', qty: 1, price: 180000 }],
  },
  {
    id: 'quo-5',
    number: 'QUO-2026-043',
    client: 'Meridian Retail Pvt Ltd',
    clientId: 'cl-4',
    amount: 141600,
    status: 'draft',
    issueDate: '2026-09-24',
    validUntil: '2026-10-09',
    taxPercent: 18,
    notes: 'Draft pending internal pricing review.',
    items: [
      { description: 'Loyalty programme module', qty: 1, price: 90000 },
      { description: 'WhatsApp order notification integration', qty: 1, price: 30000 },
    ],
  },
]
