export const projects = [
  {
    id: 'prj-1',
    name: 'Corporate Website Redesign',
    client: 'BrightPixel Labs',
    clientId: 'cl-1',
    manager: 'Jay Girase',
    status: 'active',
    progress: 68,
    budget: 620000,
    spent: 402000,
    deadline: '2026-11-05',
    startDate: '2026-06-01',
    team: ['Rohit Girase', 'Sneha Joshi', 'Tanvi Deshpande'],
    description: 'Complete redesign and rebuild of the marketing website with a new CMS.',
  },
  {
    id: 'prj-2',
    name: 'CRM Implementation',
    client: 'CloudMatrix Technologies',
    clientId: 'cl-2',
    manager: 'Jay Girase',
    status: 'active',
    progress: 42,
    budget: 1450000,
    spent: 588000,
    deadline: '2027-01-20',
    startDate: '2026-07-15',
    team: ['Amit Kulkarni', 'Rohit Girase', 'Karthik Reddy'],
    description: 'Custom CRM with lead pipeline, client portal and billing integration.',
  },
  {
    id: 'prj-3',
    name: 'E-commerce Platform',
    client: 'Meridian Retail Pvt Ltd',
    clientId: 'cl-4',
    manager: 'Jidnyasa Girase',
    status: 'planning',
    progress: 12,
    budget: 980000,
    spent: 65000,
    deadline: '2027-02-28',
    startDate: '2026-09-01',
    team: ['Sneha Joshi', 'Amit Kulkarni'],
    description: 'Headless e-commerce storefront with a custom order management backend.',
  },
  {
    id: 'prj-4',
    name: 'Mobile Application — InnoSoft',
    client: 'InnoSoft Systems',
    clientId: 'cl-3',
    manager: 'Jay Girase',
    status: 'on_hold',
    progress: 30,
    budget: 760000,
    spent: 210000,
    deadline: '2026-12-15',
    startDate: '2026-05-20',
    team: ['Rohit Girase', 'Tanvi Deshpande'],
    description: 'Cross-platform mobile app paused pending client budget approval.',
  },
  {
    id: 'prj-5',
    name: 'Booking & Membership Portal',
    client: 'Coastal Hospitality Inc',
    clientId: 'cl-6',
    manager: 'Jidnyasa Girase',
    status: 'active',
    progress: 55,
    budget: 540000,
    spent: 297000,
    deadline: '2026-10-30',
    startDate: '2026-06-10',
    team: ['Sneha Joshi', 'Amit Kulkarni', 'Tanvi Deshpande'],
    description: 'Guest booking flow with a membership tier and loyalty program.',
  },
  {
    id: 'prj-6',
    name: 'Internal Analytics Dashboard',
    client: 'Zenith Financial Group',
    clientId: 'cl-5',
    manager: 'Jay Girase',
    status: 'completed',
    progress: 100,
    budget: 410000,
    spent: 398000,
    deadline: '2026-07-01',
    startDate: '2026-03-01',
    team: ['Amit Kulkarni', 'Karthik Reddy'],
    description: 'Delivered internal reporting dashboard with automated data pipelines.',
  },
]

export function getProjectById(id) {
  return projects.find((p) => p.id === id)
}
