export const TICKET_CATEGORIES = ['Technical Issue', 'Billing & Invoicing', 'Feature Request', 'Access & Permissions', 'Integration', 'General Query']

export const tickets = [
  {
    id: 'tkt-1',
    ticketId: 'TCK-2318',
    subject: 'Unable to upload files over 10MB',
    client: 'BrightPixel Labs',
    assignee: 'Amit Kulkarni',
    priority: 'high',
    status: 'open',
    category: 'Technical Issue',
    createdDate: '2026-09-19',
    description: "We're getting a timeout error when uploading design files larger than 10MB to the project files section.",
    attachments: [{ name: 'upload-error-screenshot.png', size: '412 KB' }],
    messages: [
      { from: 'Aditi Rao', role: 'client', text: 'Getting a timeout error on large file uploads.', time: '2026-09-19T09:12:00', attachments: [{ name: 'upload-error-screenshot.png', size: '412 KB' }] },
      { from: 'Amit Kulkarni', role: 'employee', text: "Thanks for flagging — we're investigating the upload limit now.", time: '2026-09-19T10:05:00' },
    ],
    internalNotes: [
      { from: 'Amit Kulkarni', role: 'employee', text: 'Nginx client_max_body_size is set to 10m on staging. Will raise it to 50m and redeploy.', time: '2026-09-19T10:20:00' },
    ],
  },
  {
    id: 'tkt-2',
    ticketId: 'TCK-2321',
    subject: 'Request to add a new team member to project',
    client: 'CloudMatrix Technologies',
    assignee: 'Jay Girase',
    priority: 'low',
    status: 'in_progress',
    category: 'Access & Permissions',
    createdDate: '2026-09-20',
    description: 'Please add our new product manager as a viewer on the CRM Implementation project.',
    attachments: [],
    messages: [
      { from: 'Karan Mehta', role: 'client', text: 'Please add our new PM as a viewer.', time: '2026-09-20T11:00:00' },
    ],
    internalNotes: [],
  },
  {
    id: 'tkt-3',
    ticketId: 'TCK-2305',
    subject: 'Invoice PDF shows incorrect GST amount',
    client: 'InnoSoft Systems',
    assignee: 'Jidnyasa Girase',
    priority: 'urgent',
    status: 'waiting_for_client',
    category: 'Billing & Invoicing',
    createdDate: '2026-09-12',
    description: 'The GST calculation on INV-2026-00131 seems off — please confirm the correct GSTIN on file.',
    attachments: [{ name: 'INV-2026-00131.pdf', size: '186 KB' }],
    messages: [
      { from: 'Neha Kapoor', role: 'client', text: 'GST amount looks incorrect on the latest invoice.', time: '2026-09-12T15:30:00', attachments: [{ name: 'INV-2026-00131.pdf', size: '186 KB' }] },
      { from: 'Jidnyasa Girase', role: 'employee', text: 'Could you confirm the GSTIN we have on file is correct?', time: '2026-09-13T09:00:00' },
    ],
    internalNotes: [
      { from: 'Jidnyasa Girase', role: 'employee', text: 'IGST was applied instead of CGST + SGST because the client state was saved as Karnataka. Verify the GSTIN state code before reissuing.', time: '2026-09-13T09:10:00' },
    ],
  },
  {
    id: 'tkt-4',
    ticketId: 'TCK-2298',
    subject: 'Booking calendar not syncing with Google Calendar',
    client: 'Coastal Hospitality Inc',
    assignee: 'Sneha Joshi',
    priority: 'medium',
    status: 'resolved',
    category: 'Integration',
    createdDate: '2026-09-06',
    description: 'Bookings made on the portal are not appearing on the connected Google Calendar.',
    attachments: [],
    messages: [
      { from: 'Farhan Sheikh', role: 'client', text: 'Calendar sync stopped working since last week.', time: '2026-09-06T08:40:00' },
      { from: 'Sneha Joshi', role: 'employee', text: 'Fixed — the OAuth token had expired, reconnected it.', time: '2026-09-07T13:10:00' },
    ],
    internalNotes: [],
  },
  {
    id: 'tkt-5',
    ticketId: 'TCK-2276',
    subject: 'Add dark mode to client portal',
    client: 'Zenith Financial Group',
    assignee: 'Rohit Girase',
    priority: 'low',
    status: 'closed',
    category: 'Feature Request',
    createdDate: '2026-08-22',
    description: 'Feature request — client would like a dark theme option in their portal.',
    attachments: [],
    messages: [{ from: 'Ritu Malhotra', role: 'client', text: 'Would love a dark mode option.', time: '2026-08-22T12:00:00' }],
    internalNotes: [],
  },
  {
    id: 'tkt-6',
    ticketId: 'TCK-2324',
    subject: 'Password reset email lands in spam folder',
    client: 'Meridian Retail Pvt Ltd',
    assignee: 'Karthik Reddy',
    priority: 'medium',
    status: 'open',
    category: 'Technical Issue',
    createdDate: '2026-09-22',
    description: 'Our staff are not receiving password reset emails in their inbox; they land in spam for the meridianretail.in domain.',
    attachments: [],
    messages: [
      { from: 'Suresh Pillai', role: 'client', text: 'Reset emails go to spam for everyone on our domain.', time: '2026-09-22T10:15:00' },
    ],
    internalNotes: [],
  },
  {
    id: 'tkt-7',
    ticketId: 'TCK-2326',
    subject: 'Export leads to Excel fails for more than 500 rows',
    client: 'BrightPixel Labs',
    assignee: 'Rohit Girase',
    priority: 'high',
    status: 'in_progress',
    category: 'Technical Issue',
    createdDate: '2026-09-23',
    description: 'The Excel export button spins forever when we try to export the full lead list (about 620 rows).',
    attachments: [{ name: 'leads-export-console.txt', size: '8 KB' }],
    messages: [
      { from: 'Aditi Rao', role: 'client', text: 'Export never completes for the full lead list.', time: '2026-09-23T09:45:00' },
      { from: 'Rohit Girase', role: 'employee', text: 'Reproduced on our side. Working on a chunked export.', time: '2026-09-23T11:30:00' },
    ],
    internalNotes: [],
  },
  {
    id: 'tkt-8',
    ticketId: 'TCK-2289',
    subject: 'Need Razorpay settlement report in portal',
    client: 'Meridian Retail Pvt Ltd',
    assignee: 'Amit Kulkarni',
    priority: 'medium',
    status: 'resolved',
    category: 'Feature Request',
    createdDate: '2026-08-30',
    description: 'Please add a daily Razorpay settlement report so our finance team can reconcile payouts.',
    attachments: [],
    messages: [
      { from: 'Suresh Pillai', role: 'client', text: 'Can we get a settlement report in the portal?', time: '2026-08-30T14:00:00' },
      { from: 'Amit Kulkarni', role: 'employee', text: 'Released in v2.4 — find it under Payments > Settlements.', time: '2026-09-04T17:20:00' },
    ],
    internalNotes: [],
  },
  {
    id: 'tkt-9',
    ticketId: 'TCK-2312',
    subject: 'User unable to log in after role change',
    client: 'CloudMatrix Technologies',
    assignee: 'Jay Girase',
    priority: 'urgent',
    status: 'resolved',
    category: 'Access & Permissions',
    createdDate: '2026-09-16',
    description: 'One of our managers was moved to a Viewer role and now sees a blank dashboard after login.',
    attachments: [],
    messages: [
      { from: 'Karan Mehta', role: 'client', text: 'Blank dashboard after the role change.', time: '2026-09-16T08:30:00' },
      { from: 'Jay Girase', role: 'employee', text: 'Cache issue on the permission service — cleared and verified.', time: '2026-09-16T10:00:00' },
    ],
    internalNotes: [],
  },
  {
    id: 'tkt-10',
    ticketId: 'TCK-2267',
    subject: 'Quarterly billing summary format request',
    client: 'Zenith Financial Group',
    assignee: 'Jidnyasa Girase',
    priority: 'low',
    status: 'closed',
    category: 'General Query',
    createdDate: '2026-08-14',
    description: 'Can the quarterly summary be shared as an Excel sheet along with the PDF?',
    attachments: [],
    messages: [{ from: 'Ritu Malhotra', role: 'client', text: 'An Excel version would help our audit team.', time: '2026-08-14T16:10:00' }],
    internalNotes: [],
  },
  {
    id: 'tkt-11',
    ticketId: 'TCK-2329',
    subject: 'Mobile app crashes on Android 12 at login',
    client: 'InnoSoft Systems',
    assignee: 'Tanvi Deshpande',
    priority: 'urgent',
    status: 'open',
    category: 'Technical Issue',
    createdDate: '2026-09-25',
    description: 'Beta build crashes right after tapping Sign In on a Pixel 6 (Android 12). Crash log attached.',
    attachments: [{ name: 'crash-log-pixel6.txt', size: '24 KB' }],
    messages: [
      { from: 'Neha Kapoor', role: 'client', text: 'Beta build crashes immediately on Android 12.', time: '2026-09-25T08:50:00', attachments: [{ name: 'crash-log-pixel6.txt', size: '24 KB' }] },
    ],
    internalNotes: [],
  },
  {
    id: 'tkt-12',
    ticketId: 'TCK-2331',
    subject: 'Change billing contact email for invoices',
    client: 'Coastal Hospitality Inc',
    assignee: 'Pooja Nair',
    priority: 'low',
    status: 'waiting_for_client',
    category: 'Billing & Invoicing',
    createdDate: '2026-09-24',
    description: 'Send all future invoices to accounts@coastalhospitality.com instead of the GM email.',
    attachments: [],
    messages: [
      { from: 'Farhan Sheikh', role: 'client', text: 'Please route invoices to our accounts mailbox.', time: '2026-09-24T12:05:00' },
      { from: 'Pooja Nair', role: 'employee', text: 'Sure — can you confirm the mailbox owner so we can verify?', time: '2026-09-24T14:30:00' },
    ],
    internalNotes: [],
  },
]

export function getTicketById(id) {
  return tickets.find((t) => t.id === id)
}
