// Triggers a browser download for mock content (no backend files exist).
export function downloadTextFile(filename, content, mime = 'text/plain') {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  link.remove()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

export function downloadMockDocument(doc) {
  const body = [
    'WorkFlow360 - demo document',
    '',
    `File: ${doc.name}`,
    doc.category ? `Category: ${doc.category}` : null,
    doc.project ? `Project: ${doc.project}` : null,
    doc.uploadedBy ? `Uploaded by: ${doc.uploadedBy}` : null,
    doc.uploadedDate ? `Uploaded on: ${doc.uploadedDate}` : null,
    '',
    'This is placeholder content generated by the frontend demo. Real files are served by the backend.',
  ]
    .filter((line) => line !== null)
    .join('\n')
  downloadTextFile(`${doc.name.replace(/\.[^.]+$/, '')}-demo.txt`, body)
}
