import { formatCurrency, formatDate } from './format'
import { TODAY } from '../mockData/reference'

export function invoiceTotals(invoice) {
  const subtotal = (invoice.items || []).reduce((sum, item) => sum + item.qty * item.price, 0)
  const taxAmount = Math.round((subtotal * (invoice.taxPercent || 0)) / 100)
  const discount = invoice.discount || 0
  return { subtotal, taxAmount, discount, total: subtotal + taxAmount - discount }
}

// Invoice display status: an unpaid invoice past its due date reads as overdue.
export function displayStatus(invoice) {
  if (invoice.status !== 'paid' && invoice.balance > 0 && invoice.dueDate < TODAY) return 'overdue'
  return invoice.status
}

// Payment status derived from amounts, independent of the workflow status.
export function paymentStatus(invoice) {
  if (invoice.balance <= 0) return 'paid'
  if (invoice.paid > 0) return 'partially_paid'
  return 'pending'
}

function escapeHtml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

// Self-contained, printable invoice (opened or saved by the browser).
export function buildInvoiceHtml(invoice, billTo) {
  const t = invoiceTotals(invoice)
  const rows = invoice.items
    .map(
      (item) =>
        `<tr><td>${escapeHtml(item.description)}</td><td class="r">${item.qty}</td><td class="r">${escapeHtml(formatCurrency(item.price))}</td><td class="r">${escapeHtml(formatCurrency(item.qty * item.price))}</td></tr>`
    )
    .join('')
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>${escapeHtml(invoice.number)}</title>
<style>
body{font-family:Inter,Arial,Helvetica,sans-serif;color:#1f2622;margin:40px;max-width:760px}
h1{font-size:22px;margin:0;color:#0f7066}.muted{color:#737e76;font-size:13px}
table{width:100%;border-collapse:collapse;margin-top:24px}th,td{padding:10px 8px;border-bottom:1px solid #e2e6e1;font-size:14px;text-align:left}
th{border-bottom:2px solid #1aa996;background:#effcf9;color:#0f7066;font-size:12px;text-transform:uppercase;letter-spacing:.04em}.r{text-align:right}
.tot{margin-top:16px;margin-left:auto;width:280px;font-size:14px}.tot div{display:flex;justify-content:space-between;padding:4px 0}
.b{font-weight:700;border-top:2px solid #0f8c7d;margin-top:6px;padding-top:8px}
</style></head><body>
<div style="display:flex;justify-content:space-between;gap:24px">
<div><h1>TechNova Solutions</h1><p class="muted">Baner Road, Pune, Maharashtra 411045<br>hello@technova.in</p></div>
<div style="text-align:right"><h1>INVOICE</h1><p class="muted">${escapeHtml(invoice.number)}<br>Issued ${escapeHtml(formatDate(invoice.issueDate))}<br>Due ${escapeHtml(formatDate(invoice.dueDate))}</p></div>
</div>
<p style="margin-top:28px"><span class="muted">Billed to</span><br><strong>${escapeHtml(billTo)}</strong></p>
<table><thead><tr><th>Description</th><th class="r">Qty</th><th class="r">Rate</th><th class="r">Amount</th></tr></thead><tbody>${rows}</tbody></table>
<div class="tot">
<div><span>Subtotal</span><span>${escapeHtml(formatCurrency(t.subtotal))}</span></div>
${invoice.taxPercent ? `<div><span>GST (${invoice.taxPercent}%)</span><span>${escapeHtml(formatCurrency(t.taxAmount))}</span></div>` : ''}
${t.discount ? `<div><span>Discount</span><span>-${escapeHtml(formatCurrency(t.discount))}</span></div>` : ''}
<div class="b"><span>Total</span><span>${escapeHtml(formatCurrency(t.total))}</span></div>
<div><span>Paid</span><span>${escapeHtml(formatCurrency(invoice.paid))}</span></div>
<div class="b"><span>Balance due</span><span>${escapeHtml(formatCurrency(invoice.balance))}</span></div>
</div>
${invoice.notes ? `<p class="muted" style="margin-top:28px">${escapeHtml(invoice.notes)}</p>` : ''}
<p class="muted">Payment terms: ${escapeHtml(invoice.paymentTerms || 'Net 15')}. This is a demo document generated by WorkFlow360.</p>
</body></html>`
}
